title: rafa nascimento
description: TBD2
author: "Rafa Nascimento"

theme: minima

base_url: /blog

# Minima social links
github_username: nascimentorafael
linkedin_username: rafaellnascimentoo

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
